#!/usr/bin/env bash
# shellcheck disable=SC1091,SC2034  # scripts/lib/sync-exclusions.sh reads EXCLUDED; shellcheck can't follow a dynamic source path without -x
# Keep the vendored Matt Pocock skills in `.agents/skills/` current; `--fetch`
# re-vendors from upstream first. `UPSTREAM.json` records this sync's names and
# gates deletion. `scripts/sync-pstack.sh` owns the `.claude`/`.cursor` symlinks.

set -euo pipefail

REPO=https://github.com/mattpocock/skills
BRANCH=main
SUBPATH=skills/engineering

root=$(git rev-parse --show-toplevel)
cd "$root"

SKILLS=.agents/skills
META=.agents/mattpocock/UPSTREAM.json
PSTACK_META=.agents/pstack/UPSTREAM.json

# Names upstream ships that this sync does not vendor, one `name|reason` per
# line. It drives both the skip and the lock file's `excluded` block. Reasons
# go into JSON verbatim, so no double quotes.
EXCLUDED='ask-matt|Policy. A router over the whole upstream set, including the four groups this repository does not vendor, so most of what it offers is not here. docs/agents/picking-work.md decides what to work on.
setup-matt-pocock-skills|Already run here, and a re-run only does damage. It scaffolds docs/agents/issue-tracker.md, docs/agents/triage-labels.md and docs/agents/domain.md plus the Agent skills block in AGENTS.md; all four exist and have been hand-edited since. Its step 4 also prefers CLAUDE.md, which here only points at AGENTS.md, so a re-run would write a second Agent skills block into the file that does nothing else. See docs/agents/vendored-skills.md.'

source "$(dirname "${BASH_SOURCE[0]}")/lib/sync-exclusions.sh"

# A missing lock file owns nothing, so the first `--fetch` deletes nothing.
owned_names() {
  [ -f "$1" ] || return 0
  awk '
    /"skills": \[/ { inlist = 1; next }
    inlist && /^[[:space:]]*\]/ { inlist = 0 }
    inlist { gsub(/[ \t",]/, ""); if ($0 != "") print }
  ' "$1"
}

mine() { owned_names "$META"; }

# Names this sync must never write or delete: everything pstack owns, plus any
# directory neither lock file claims, which this repository wrote. Computed
# rather than hand-listed, so it also covers a collision upstream adds later.
reserved_names() {
  local pstack_owned
  pstack_owned=$(owned_names "$PSTACK_META" | sort)
  {
    echo "$pstack_owned"
    comm -23 \
      <(find "$SKILLS" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | sort) \
      <(sort -u <(echo "$pstack_owned") <(mine | sort))
  } | sort -u
}

if [ "${1:-}" = "--fetch" ]; then
  tmp=$(mktemp -d)
  # shellcheck disable=SC2064  # expand tmp now, not at trap time
  trap "rm -rf '$tmp'" EXIT

  git clone --quiet --filter=blob:none --sparse --depth 1 -b "$BRANCH" \
    "$REPO" "$tmp/skills"
  git -C "$tmp/skills" sparse-checkout set --skip-checks "$SUBPATH" LICENSE
  up=$tmp/skills/$SUBPATH

  before=$(mine | sort)
  # Upstream's listing drives the rsync; the lock file only records the last
  # sync. Dropping a name from the lock file would not keep it out, which is
  # what `EXCLUDED` is for.
  upstream=$(find "$up" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | sort)
  reserved=$(reserved_names)

  candidates=$(comm -23 <(echo "$upstream") <(excluded_names))
  after=$(comm -23 <(echo "$candidates") <(echo "$reserved"))
  comm -12 <(echo "$candidates") <(echo "$reserved") | while read -r clash; do
    [ -n "$clash" ] || continue
    echo "skipping $clash (name already owned by pstack or by this repository)"
  done

  # Only names this script owned are eligible, so a pstack or repo-owned skill
  # is never removed here.
  comm -23 <(echo "$before") <(echo "$after") | while read -r gone; do
    [ -n "$gone" ] || continue
    echo "removing $gone (gone from upstream, excluded, or now reserved)"
    rm -rf "${SKILLS:?}/$gone"
  done

  while read -r name; do
    [ -n "$name" ] || continue
    rsync -a --delete "$up/$name/" "$SKILLS/$name/"
  done <<< "$after"

  cp "$tmp/skills/LICENSE" .agents/mattpocock/LICENSE

  sha=$(git -C "$tmp/skills" rev-parse HEAD)

  # Without jq, so this runs on a bare macOS checkout.
  {
    echo '{'
    echo '  "_warning": "Generated by scripts/sync-mattpocock.sh and .github/workflows/mattpocock-skills-sync.yml. Do not hand-edit.",'
    echo "  \"repository\": \"$REPO\","
    echo "  \"subpath\": \"$SUBPATH\","
    echo "  \"branch\": \"$BRANCH\","
    echo "  \"commit\": \"$sha\","
    echo '  "license": "MIT",'
    echo "  \"synced\": \"$(date -u +%Y-%m-%d)\","
    echo '  "vendored_into": ".agents/skills",'
    echo '  "not_vendored": ["skills/deprecated", "skills/in-progress", "skills/misc", "skills/productivity"],'
    echo '  "_excluded": "Names upstream ships under the subpath that this sync deliberately does not vendor. Generated from EXCLUDED in scripts/sync-mattpocock.sh.",'
    echo '  "excluded": {'
    excluded_json
    echo '  },'
    echo '  "_skills": "The skill directories under .agents/skills this file owns. Anything else there belongs to pstack or to this repository and is never touched by this sync.",'
    echo '  "skills": ['
    echo "$after" | sed '$ !s/.*/    "&",/; $ s/.*/    "&"/'
    echo '  ]'
    echo '}'
  } > "$META"
fi

# The index: one line per skill from its frontmatter `description`, so an agent
# can find a skill without reading every SKILL.md.
{
  echo "# Matt Pocock engineering skills"
  echo
  echo "Generated by \`scripts/sync-mattpocock.sh\`. Do not hand-edit."
  echo
  echo "One line per vendored skill, taken from its frontmatter. They live in"
  echo "\`.agents/skills/\`, alongside the pstack skills and the ones this"
  echo "repository owns, neither of which is listed here. None of them is on by"
  echo "default. Apply one when the user names it, by reading"
  echo "\`.agents/skills/<name>/SKILL.md\` and following it."
  echo
  while read -r name; do
    [ -n "$name" ] || continue
    # A folded block scalar (`>-`) continues on indented lines; join them.
    desc=$(awk '
      /^description:/ {
        sub(/^description:[ \t]*/, "")
        if ($0 ~ /^[>|]/) {
          out = ""
          while ((getline line) > 0) {
            if (line !~ /^[ \t]+/) break
            sub(/^[ \t]+/, "", line)
            out = (out == "" ? line : out " " line)
          }
          print out
        } else {
          print
        }
        exit
      }
    ' "$SKILLS/$name/SKILL.md" | sed 's/^"//; s/"$//; s/\\"/"/g')
    echo "- \`$name\` — $desc"
  done < <(mine)
} > .agents/mattpocock/SKILLS.md

echo "$(mine | grep -c .) vendored Matt Pocock skills in $SKILLS ($(find "$SKILLS" -mindepth 1 -maxdepth 1 -type d | wc -l | tr -d ' ') total)"
